"""Pydantic models for the assistant endpoints."""

import re
from typing import Any
from pydantic import BaseModel, Field, field_validator


# ── /ask ──────────────────────────────────────────────────────────────────────

class AskRequest(BaseModel):
    question: str = Field(..., min_length=3, max_length=1000)
    top_k: int = Field(default=5, ge=1, le=20)

    @field_validator("question")
    @classmethod
    def sanitize_question(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Question cannot be empty or whitespace only.")
        # Strip potential HTML/script tags for security
        clean = re.sub(r"<[^>]*>", "", v)
        clean = " ".join(clean.strip().split())
        if len(clean) < 3:
            raise ValueError("Question is too short after sanitization.")
        return clean


class SourceMetadata(BaseModel):
    """Clean source metadata without raw content or similarity scores."""
    source: str
    page: int | None = None


class AskResponse(BaseModel):
    """Professional AI Cost Intelligence Assistant response."""
    question: str
    route: str
    answer: str
    explanation: str  # Business insights generated by LLM
    sources: list[SourceMetadata] = []
    model_used: str
    suggestions: list[str] = Field(
        default_factory=list,
        description="2–3 contextual follow-up question suggestions based on the response",
    )
