"""Application-level constants and limits."""

APP_NAME_DEFAULT = "Cloud Cost Intelligence"
APP_VERSION_DEFAULT = "1.0.0"

DEFAULT_TOP_K = 5
DEFAULT_PAGINATION_SIZE = 10
DEFAULT_REQUEST_TIMEOUT_SECONDS = 30
MAX_UPLOAD_SIZE_BYTES = 10_485_760  # 10 MB

DEFAULT_DOWNLOAD_DIR = "downloads"
DEFAULT_LOG_DIR = "logs"
DEFAULT_LOG_LEVEL = "INFO"
