"""AWS-related constants and default fallback values."""

S3_BUCKET_DEFAULT = "awscost359"
S3_ACCOUNT_MASTER_PREFIX_DEFAULT = "account_master/"
S3_ACCOUNT_MASTER_FILE_DEFAULT = "account_master/Account.csv"
S3_COST_EXPLORER_PREFIX_DEFAULT = "cost-explorer/"

AWS_REGION_DEFAULT = "us-east-1"

BEDROCK_MODEL_ID_DEFAULT = "us.anthropic.claude-3-5-haiku-20241022-v1:0"
BEDROCK_MAX_TOKENS_DEFAULT = 2048
BEDROCK_TEMPERATURE_DEFAULT = 0.2
BEDROCK_TOP_P_DEFAULT = 1.0

AWS_CONNECT_TIMEOUT_DEFAULT = 10
AWS_READ_TIMEOUT_DEFAULT = 30
AWS_MAX_RETRIES_DEFAULT = 3
